
package com.inflationinrussia.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServices", targetNamespace = "http://www.inflationinrussia.com/WebServices", wsdlLocation = "http://xn----ctbjnaatncev9av3a8f8b.xn--p1ai/DesktopModules/WebServices.asmx?WSDL")
public class WebServices
    extends Service
{

    private final static URL WEBSERVICES_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICES_EXCEPTION;
    private final static QName WEBSERVICES_QNAME = new QName("http://www.inflationinrussia.com/WebServices", "WebServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://xn----ctbjnaatncev9av3a8f8b.xn--p1ai/DesktopModules/WebServices.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICES_WSDL_LOCATION = url;
        WEBSERVICES_EXCEPTION = e;
    }

    public WebServices() {
        super(__getWsdlLocation(), WEBSERVICES_QNAME);
    }

    public WebServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICES_QNAME, features);
    }

    public WebServices(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICES_QNAME);
    }

    public WebServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICES_QNAME, features);
    }

    public WebServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServicesSoap
     */
    @WebEndpoint(name = "WebServicesSoap")
    public WebServicesSoap getWebServicesSoap() {
        return super.getPort(new QName("http://www.inflationinrussia.com/WebServices", "WebServicesSoap"), WebServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServicesSoap
     */
    @WebEndpoint(name = "WebServicesSoap")
    public WebServicesSoap getWebServicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.inflationinrussia.com/WebServices", "WebServicesSoap"), WebServicesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICES_EXCEPTION!= null) {
            throw WEBSERVICES_EXCEPTION;
        }
        return WEBSERVICES_WSDL_LOCATION;
    }

}
