
package com.inflationinrussia.webservices;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServicesSoap", targetNamespace = "http://www.inflationinrussia.com/WebServices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServicesSoap {


    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetFirstMonth", action = "http://www.inflationinrussia.com/WebServices/GetFirstMonth")
    @WebResult(name = "GetFirstMonthResult", targetNamespace = "http://www.inflationinrussia.com/WebServices")
    @RequestWrapper(localName = "GetFirstMonth", targetNamespace = "http://www.inflationinrussia.com/WebServices", className = "com.inflationinrussia.webservices.GetFirstMonth")
    @ResponseWrapper(localName = "GetFirstMonthResponse", targetNamespace = "http://www.inflationinrussia.com/WebServices", className = "com.inflationinrussia.webservices.GetFirstMonthResponse")
    public XMLGregorianCalendar getFirstMonth();

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetLastMonth", action = "http://www.inflationinrussia.com/WebServices/GetLastMonth")
    @WebResult(name = "GetLastMonthResult", targetNamespace = "http://www.inflationinrussia.com/WebServices")
    @RequestWrapper(localName = "GetLastMonth", targetNamespace = "http://www.inflationinrussia.com/WebServices", className = "com.inflationinrussia.webservices.GetLastMonth")
    @ResponseWrapper(localName = "GetLastMonthResponse", targetNamespace = "http://www.inflationinrussia.com/WebServices", className = "com.inflationinrussia.webservices.GetLastMonthResponse")
    public XMLGregorianCalendar getLastMonth();

    /**
     * 
     * @param startMonth
     * @param endMonth
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetInflation", action = "http://www.inflationinrussia.com/WebServices/GetInflation")
    @WebResult(name = "GetInflationResult", targetNamespace = "http://www.inflationinrussia.com/WebServices")
    @RequestWrapper(localName = "GetInflation", targetNamespace = "http://www.inflationinrussia.com/WebServices", className = "com.inflationinrussia.webservices.GetInflation")
    @ResponseWrapper(localName = "GetInflationResponse", targetNamespace = "http://www.inflationinrussia.com/WebServices", className = "com.inflationinrussia.webservices.GetInflationResponse")
    public BigDecimal getInflation(
        @WebParam(name = "startMonth", targetNamespace = "http://www.inflationinrussia.com/WebServices")
        XMLGregorianCalendar startMonth,
        @WebParam(name = "endMonth", targetNamespace = "http://www.inflationinrussia.com/WebServices")
        XMLGregorianCalendar endMonth);

    /**
     * 
     * @param applyDenominationOf1998
     * @param startAmount
     * @param startMonth
     * @param endMonth
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetPriceChange", action = "http://www.inflationinrussia.com/WebServices/GetPriceChange")
    @WebResult(name = "GetPriceChangeResult", targetNamespace = "http://www.inflationinrussia.com/WebServices")
    @RequestWrapper(localName = "GetPriceChange", targetNamespace = "http://www.inflationinrussia.com/WebServices", className = "com.inflationinrussia.webservices.GetPriceChange")
    @ResponseWrapper(localName = "GetPriceChangeResponse", targetNamespace = "http://www.inflationinrussia.com/WebServices", className = "com.inflationinrussia.webservices.GetPriceChangeResponse")
    public BigDecimal getPriceChange(
        @WebParam(name = "startAmount", targetNamespace = "http://www.inflationinrussia.com/WebServices")
        BigDecimal startAmount,
        @WebParam(name = "startMonth", targetNamespace = "http://www.inflationinrussia.com/WebServices")
        XMLGregorianCalendar startMonth,
        @WebParam(name = "endMonth", targetNamespace = "http://www.inflationinrussia.com/WebServices")
        XMLGregorianCalendar endMonth,
        @WebParam(name = "applyDenominationOf1998", targetNamespace = "http://www.inflationinrussia.com/WebServices")
        boolean applyDenominationOf1998);

    /**
     * 
     * @param applyDenominationOf1998
     * @param startAmount
     * @param startMonth
     * @param endMonth
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetValueChange", action = "http://www.inflationinrussia.com/WebServices/GetValueChange")
    @WebResult(name = "GetValueChangeResult", targetNamespace = "http://www.inflationinrussia.com/WebServices")
    @RequestWrapper(localName = "GetValueChange", targetNamespace = "http://www.inflationinrussia.com/WebServices", className = "com.inflationinrussia.webservices.GetValueChange")
    @ResponseWrapper(localName = "GetValueChangeResponse", targetNamespace = "http://www.inflationinrussia.com/WebServices", className = "com.inflationinrussia.webservices.GetValueChangeResponse")
    public BigDecimal getValueChange(
        @WebParam(name = "startAmount", targetNamespace = "http://www.inflationinrussia.com/WebServices")
        BigDecimal startAmount,
        @WebParam(name = "startMonth", targetNamespace = "http://www.inflationinrussia.com/WebServices")
        XMLGregorianCalendar startMonth,
        @WebParam(name = "endMonth", targetNamespace = "http://www.inflationinrussia.com/WebServices")
        XMLGregorianCalendar endMonth,
        @WebParam(name = "applyDenominationOf1998", targetNamespace = "http://www.inflationinrussia.com/WebServices")
        boolean applyDenominationOf1998);

}
